### DISCUSSION TITLE
medium/large files upload

### DISCUSSION THREAD

**Discussion by unlucio** [HemmeligOrg/Hemmelig.app#320] [Q&A]
Hello, I'm trying to send 378 images (552 MB) to a friend using my hemmeling instance but for some reason I'm failing.

This is the compose file I'm using:
```yaml
version: '3.8'

services:
  hemmelig:
    image: hemmeligapp/hemmelig:latest
    environment:
      - TZ=Europe/Rome
      - SECRET_HOST=public.url.com
      - SECRET_ROOT_USER=root # User as the root admin user
      - SECRET_ROOT_PASSWORD=rootpassword
      - SECRET_ROOT_EMAIL=my@email.com
      - SECRET_FILE_SIZE=10000
      - SECRET_FORCED_LANGUAGE=en
      - SECRET_JWT_SECRET=supersecretsecret
      - SECRET_MAX_TEXT_SIZE=1024
    volumes:
      - /mnt/data/hemmelig/data:/var/tmp/hemmelig/upload/files
      - /mnt/data/hemmelig/db:/home/node/hemmelig/database
    expose:
     - 3000:3000
```

If I upload them as a 542.3Mb zip file, I get a 272b hemmelig_files.zip file containing a zero bytes zipfile.
checking the browser's network tab I noticed the following:
```
curl 'https://public.url.com/api/secret' \
  -H 'accept: */*' \
  -H 'accept-language: en-GB,en;q=0.8' \
  -H 'cache-control: max-age=0' \
  -H 'content-type: application/json' \
  -H $'cookie: ulToken=1_HJZDggd\u0021o9jCfS5WTmw9OuTkGAaDyj; __HEMMELIG_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imx1Y2lvIiwiZW1haWwiOiJ1bmx1Y2lvK3NzQGdtYWlsLmNvbSIsInVzZXJfaWQiOiI4OGU0ZDExMC0wZTg4LTQ5OTItYjAwNS0wYTk5YmEyOTk4YmEiLCJpYXQiOjE3Mjc3ODAxMzIsImV4cCI6MTcyODM4NDkzMn0.DkSlP9n9vFAJRN-CvC4z8YAjBm4HcpqOb5BweFFoZVo; __HEMMELIG_TOKEN_PUBLIC=eyJ1c2VybmFtZSI6Imx1Y2lvIn0%3D' \
  -H 'origin: https://public.url.com' \
  -H 'priority: u=1, i' \
  -H 'sec-ch-ua: "Brave";v="129", "Not=A?Brand";v="8", "Chromium";v="129"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'sec-gpc: 1' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36' \
  --data-raw '{"text":"z8xquWSPn8Bls12n3hs9qG4Lx/WENcHYTZ0mpE4W7l/vyaaCSSZdqKj6u3Xt6JXbI/6s","files":[{"type":"application/zip","ext":".zip","content":"we3Nxj5wg0ttUxoiz+ApoES4kZhv+jP0FUjDleVeO9jDyrVTWBGpTEoVg/jYbURzlFLu9an41wPZsVJMrz6RgmAva6b1KTJ8HlNpbwypjUzfuZq5VuSIWDLUAglIN2Xii2Ah+Oy/bSbQtrfZ/e6YyJLRecAZ7ikkuwg72LshvIbAQJlUZzeISyXv+3Sk8YkI7eRNrd0d1KDRakgLVx5OklPAwaPmBs+W3q8b5kIA5pyPy/xOFmiSdcJ3kLNXl9GLWMN7uraz8v36QGgdls8VDuwdtwPskkFn7+/8EHaCcvU+e3w9skvmVimcGx3i4BMAjCq8+xEuIfP3n/h06f7gE91wLrQN9bBs8/+N2/MfGXCCIXkPot5X8j4RXtNarmW1O+eCrp76Bdz//SLKGEJYaYx8S879RPCFBm/Kzl62kiao6i38zKpedDGJIVwfininD6bZbHk4ZN9NCUkWi8Vncfc0hAHTpVPkTVth05MBPm2RSiGFVdLhQfuSjpPu5ol+C7IB12OaVlpSwQpKIevvlAAsXe8="}],"title":"NlnRyeESIy59tXE1Gx6IRlasihfA+9fBAGzI3zyhMKEJxP9yWMiiEyv0GeQ=","password":"","ttl":1209600,"allowedIp":"","preventBurn":false,"maxViews":100,"isPublic":false}'
```
the `files[0].content` base64 is nothing near the zipfile I need to upload, what gives?
