### ISSUE TITLE
Stuck Issue (Blank Screen) when using ARM version

### ISSUE THREAD

**Issue by cevinov** [HemmeligOrg/Hemmelig.app#183]
### Description

Hello I try self-hosting hemmelig-app using my ARM linux instance (Oracle Linux 8.7).

**Command :**
docker run -p 3000:3000 -d --name=hemmelig \
   -v /hemmelig-secret:/var/tmp/hemmelig/upload/files \
   -v /hemmelig-secret/db:/home/node/hemmelig/database/ \
   hemmeligapp/hemmelig:arm-latest

But here is the problem, when I try to hit URL http://ip-address: 3000 it just shows a white screen to me (No content is shown).

**Evidence :**
https://screenrec.com/share/qd9rlJIZDN

### Screenshots

![image](https://user-images.githubusercontent.com/94840989/232707089-09240a03-a323-4b85-8fcd-fb86d9d7e48e.png)

### Additional information

Log Files
[_hemmelig_logs.txt](https://github.com/HemmeligOrg/Hemmelig.app/files/11259189/_hemmelig_logs.txt)

**Comment by bjarneo** [comment]
Hi @cevinov,

Thanks. This is a common issue as it tries to fetch content from the HTTPS protocol. We are looking into solving this as many people want to try the application without putting it behind a reverse proxy.

If you add a reverse proxy with ssl/tls termination in front, it will work as expected.

Will keep this issue open.

**Comment by bjarneo** [comment]
ALSO, the latest ARM version is using the 4 version, which means it needs redis. There is an issue with Prisma and ARM creation of the docker images that has to be solved https://github.com/HemmeligOrg/Hemmelig.app/issues/171

**Comment by cevinov** [comment]
Hello @bjarneo,

Regarding your suggestion using reverse proxy, it works Thanks...
![image](https://user-images.githubusercontent.com/94840989/232745817-28ce2970-e7a7-4a69-b2a6-562c94490aa6.png)

**Comment by bjarneo** [comment]
Great that the first part worked. What version of Hemmelig are you using? As mentioned above, the ARM is before the version 5, which means different documentation. Here the user part will not work.

**Comment by cevinov** [comment]
I'm using the latest for the ARM version.
![image](https://user-images.githubusercontent.com/94840989/232809022-80943249-52e8-4e11-83ad-f16066d97198.png)

yml :

services:
hemmelig:
image: hemmeligapp/hemmelig:arm-latest # Check the tags for what version to use
hostname: hemmelig
init: true
volumes:
- /hemmelig-secret:/var/tmp/hemmelig/upload/files
- /hemmelig-secret/db:/home/node/hemmelig/database/
environment:
- SECRET_LOCAL_HOSTNAME=ip-address # The local hostname for the fastify instance
- SECRET_PORT=3000 # The port number for the fastify instance
- SECRET_HOST=change # Used for i.e. set cors/cookies to your domain name
- SECRET_ROOT_USER=change # User as the root admin user
- SECRET_ROOT_PASSWORD=change # The admin user password (change this after signed in)
- SECRET_ROOT_EMAIL=change@gmail.com # The email for the admin user
- SECRET_FILE_SIZE=50000 # Set the total allowed upload file size in mb
- SECRET_FORCED_LANGUAGE=en # Set the default language for the application
- SECRET_JWT_SECRET=change # Override this for the secret signin JWT tokens for log in
- SECRET_MAX_TEXT_SIZE=20000 # The max text size for the secret. Is set in kb. i.e. 256 for 256kb
ports:
- '7751:3000'
restart: always
stop_grace_period: 1m
healthcheck:
test: 'wget -O /dev/null ip-address:3000 || exit 1'
timeout: 5s
retries: 1

**Comment by bjarneo** [comment]
@cevinov Try this docker compose file. It is from before the version 5 release:
https://github.com/HemmeligOrg/Hemmelig.app/blob/3a50974717b4b5eb12eeb1a386f0c44b4f37af06/docker-compose.yml

And as mentioned, the ARM build is running on the version 4 until a bug is fixed.

**Comment by cevinov** [comment]
I see, when i use this image : hemmeligapp/hemmelig:arm-latest, it shows an error like **no matching manifest for linux/arm64/v8 in the manifest list entries**.
![image](https://user-images.githubusercontent.com/94840989/232833602-1ad67cb8-6066-4bcb-adec-972ef05c5593.png)

![image](https://user-images.githubusercontent.com/94840989/232833697-508f2429-eaff-4a90-a8fb-7f49d49cf4fb.png)

**Comment by bjarneo** [comment]
@cevinov yes, you have to update the docker to `image: hemmeligapp/hemmelig:arm-latest`

**Comment by bjarneo** [comment]
Hopefully I have some spare time to get the newest version of Hemmelig on ARM as well.

**Comment by bjarneo** [comment]
Hm. Have a look at the redis images at docker hub. Most likely find the one
you need there.

tir. 18. apr. 2023, 18:28 skrev Cevino ***@***.***>:

**Comment by cevinov** [comment]
Found it, I try with this image redis:latest
https://hub.docker.com/_/redis/tags

But i have a problem when run the docker-compose.
![image](https://user-images.githubusercontent.com/94840989/232848530-b09e5c9c-302f-4319-92f8-eb26b84e0e31.png)

**Comment by bjarneo** [comment]
Answer to your problem: https://stackoverflow.com/questions/65456814/docker-apple-silicon-m1-preview-mysql-no-matching-manifest-for-linux-arm64-v8

A new version is coming with ARM64 support for the version you tested earlier. Use the tag v5.7.2 https://github.com/HemmeligOrg/Hemmelig.app/issues/183#issuecomment-1513260232

**Comment by cevinov** [comment]
It works now thanks for your suggestion using v5.7.2 @bjarneo 
![image](https://user-images.githubusercontent.com/94840989/233273523-fc14ec78-2bdb-4c4f-ab7c-67637e3813d3.png)

The problem on DB side, I'm not able to create a secret link if I uploaded the files.

**Comment by bjarneo** [comment]
Great!

For the file issue, have a look at the last section of the readme, and it will have a suggestion for the correct read/write rights you have to set for your docker mount.

**Comment by cevinov** [comment]
This is my log files, it says No pending migrations to apply.

![image](https://user-images.githubusercontent.com/94840989/233275602-bdde05d4-668a-4699-98d0-11946fb2fa83.png)

**Comment by bjarneo** [comment]
No, but you have to add the correct settings for the files folder as well. If you create a secret with a file, you will notice an error message saying you do not have the correct permissions to create a file.

**Comment by cevinov** [comment]
Yes i got that error, so i need to create a group first ?

**Comment by bjarneo** [comment]
Not necessarily, you just have to use a different user than root, and assign that user rights to the folders you are using as the volume for your application.

**Comment by cevinov** [comment]
Thanks for the suggestion, I already do it and I check on the logs no error found regarding DB migration. But still can't create a secret link if I attached file on it.

![image](https://user-images.githubusercontent.com/94840989/233794520-6ad6678c-0a19-4012-9c27-f03ec721cce3.png)

**Comment by bjarneo** [comment]
Is the file added to your folder outside of the running docker container? Do you get any error messages at all?

**Comment by cevinov** [comment]
Yml file I put it inside hemmelig container volume, and no error occurred during docker-compose.

**Comment by bjarneo** [comment]
what?

**Comment by cevinov** [comment]
I tried going into the account menu, and it just gives me the loading icon.
![image](https://user-images.githubusercontent.com/94840989/233801171-b8885b53-98b0-4e01-bb00-f90f857b9ecd.png)

**Comment by bjarneo** [comment]
Let me share with you my ansible setup for deploying this application to a linode server:
```yaml
- hosts: linode
  become: true
  vars:
    hemmelig_docker_image: hemmeligapp/hemmelig:v5.8.2
  tasks:
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Create a login user
      user:
        name: hemmelig
        password: "{{HEMMELIG_USER_PASSWORD}}"
        groups: # Empty by default, here we give it some groups
        - docker
        - sudo
        state: present

    - name: Pull the Hemmelig docker image for deployments
      docker_image: 
        name: "{{hemmelig_docker_image}}"
        source: pull

    - name: Start the Hemmelig.app container
      docker_container:
        name: hemmelig
        image: "{{hemmelig_docker_image}}"
        env:  
          SECRET_MASTER_KEY: "{{SECRET_MASTER_KEY}}"
          SECRET_JWT_SECRET: "{{SECRET_JWT_SECRET}}"
          SECRET_ROOT_USER: "sudosu"
          SECRET_ROOT_PASSWORD: "lolyouthinkthisisit"
          SECRET_ROOT_EMAIL: "sudosu@gmail.com"
          SECRET_MAX_TEXT_SIZE: "20048"
          SECRET_HOST: "hemmelig.app"
        ports:
          - '3000:3000'
        volumes:
          - '/home/hemmelig/userdata/:/var/tmp/hemmelig/upload/files'
          - '/home/hemmelig/database/:/home/node/hemmelig/database/'
        restart_policy: always
        network_mode: host
      tags: hemmelig
  
    - name: Set the correct permissions for the userdata
      shell: chown -R hemmelig.hemmelig /home/hemmelig/userdata/

    - name: Set the correct permissions for the database
      shell: chown -R hemmelig.hemmelig /home/hemmelig/database/

  roles:
    - role: caddy-role
      caddy_systemd_capabilities_enabled: true
      caddy_systemd_capabilities: "CAP_NET_BIND_SERVICE"
      caddy_setcap: yes
      caddy_config: |
        hemmelig.app {
          encode gzip
          header Server "Hemmelig"
          header X-Github-Repository "https://github.com/HemmeligOrg/Hemmelig.app"
          header X-Hacker "Uv. Jbhyq lbh cyrnfr ercbeg gur ihyarenovyvgvrf gb Tvguho vs lbh svaq nal? Gunaxf :)"
          header /static/* Cache-Control max-age=31536000

          reverse_proxy localhost:3000
        }
```
