### ISSUE TITLE
Restricting to specific IP Adress not working

### ISSUE THREAD

**Issue by Tonyzaa-V** [HemmeligOrg/Hemmelig.app#185]
### Description

Hi, @bjarneo appreciate your efforts.
I'm hitting this blocker when restricting the secret to a specific IP address, the secret won't open.
I tried my individual IP address and tried the CIDR/32 but this functionality isn't working for me.
I've tested this with a friend's IP address as well.

### Screenshots

<img width="993" alt="Screenshot 2023-05-05 at 2 14 48 pm" src="https://user-images.githubusercontent.com/80736734/236376767-f2825b03-d010-4610-bf0e-43d4322cd529.png">

### Additional information

I have hemmelig with docker compose behind Traefik.
```
hemmelig:
    image: hemmeligapp/hemmelig:latest # Check the tags for what version to use
    hostname: hemmelig
    container_name: hemmelig
    init: true
    volumes:
        - $DOCKERDIR/appdata/hemmelig/:/var/tmp/hemmelig/upload/files
        - $DOCKERDIR/appdata/hemmelig-database/:/home/node/hemmelig/database/
    environment:
        - SECRET_LOCAL_HOSTNAME=$SECRET_LOCAL_HOSTNAME # The local hostname for the fastify instance
        - SECRET_PORT=$SECRET_PORT # The port number for the fastify instance
        - SECRET_HOST=$SECRET_HOST # Used for i.e. set cors/cookies to your domain name
        - SECRET_ROOT_USER=$SECRET_ROOT_USER # User as the root admin user
        - SECRET_ROOT_PASSWORD=$SECRET_ROOT_PASSWORD # The admin user password (change this after signed in)
        - SECRET_ROOT_EMAIL=$SECRET_ROOT_EMAIL # The email for the admin user
        - SECRET_FILE_SIZE=$SECRET_FILE_SIZE # Set the total allowed upload file size in mb
        - SECRET_FORCED_LANGUAGE=$SECRET_FORCED_LANGUAGE # Set the default language for the application
        - SECRET_JWT_SECRET=$SECRET_JWT_SECRET # Override this for the secret signin JWT tokens for log in
        - SECRET_MAX_TEXT_SIZE=$SECRET_MAX_TEXT_SIZE # The max text size for the secret. Is set in kb. i.e. 256 for 256kb
    restart: always
    stop_grace_period: 1m
    healthcheck:
        test: 'wget -O /dev/null localhost:3000 || exit 1'
        timeout: 5s
        retries: 1
    networks:
      - proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.hemmelig-rtr.rule=Host(`hemmelig.$DOMAINNAME_CLOUD_SERVER`)'
      - 'traefik.http.routers.hemmelig-rtr.entrypoints=https'
      - 'traefik.http.routers.hemmelig-rtr.tls=true'
      - "traefik.http.routers.hemmelig-svc.middlewares=chain-authelia@file"
      - "traefik.http.routers.hemmelig-rtr.service=hemmelig-svc"
      - "traefik.http.services.hemmelig-svc.loadbalancer.server.port=3000"
 ```
