### ISSUE TITLE
[OTHER] Problems logging in 

### ISSUE THREAD

**Issue by cocoonkid** [HemmeligOrg/Hemmelig.app#248]
### What would you like to share?

```secretstestcom-hemmelig-1  | {"level":30,"time":1705593625592,"pid":19,"hostname":"1d4e5a2acc1e","reqId":"req-22","res":{"statusCode":401},"responseTime":1.379293441772461,"msg":"request completed"}```

I always get the 401 response when trying to login as admin user.
```
services:
    hemmelig:
        image: hemmeligapp/hemmelig:latest
        init: true 
        volumes:
            - ./uploads:/var/tmp/hemmelig/upload/files
            - ./database/:/home/node/hemmelig/database/  # sudo chown -R 1000:1000 database
        environment:
            - SECRET_LOCAL_HOSTNAME=0.0.0.0 # The local hostname for the fastify instance
            - SECRET_PORT=3000 # The port number for the fastify instance
            - SECRET_HOST=secrets.mysite.com # Used for i.e. set cors/cookies to your domain name
            - SECRET_ROOT_USER=groot # User as the root admin user
            - SECRET_ROOT_PASSWORD=iamroot # The admin user password (change this after signed in)
            - SECRET_ROOT_EMAIL=admin@mypage.com # The email for the admin user
            - SECRET_FILE_SIZE=4 # Set the total allowed upload file size in mb
            - SECRET_FORCED_LANGUAGE=en # Set the default language for the application
            - SECRET_JWT_SECRET=<secret> # Override this for the secret signin JWT tokens for log in
            - SECRET_MAX_TEXT_SIZE=256 # The max text size for the secret. Is set in kb. i.e. 256 for 256kb
            - SECRET_DISABLE_USERS=false
            - SECRET_ENABLE_FILE_UPLOAD=true 
```
            
            
  I have a reverse proxy in front and no CORS or similar issues with other apps. 
  The logs of that proxy usually tell me if there is an issue by they look fine. 
  
  What could the problem be?
  
  I can do everything as non-logged in user and that works fine.

### Additional information

![image](https://github.com/HemmeligOrg/Hemmelig.app/assets/43231640/e7b2a692-c958-4338-9765-dea38ffcc246)
That's all i can see.
