### ISSUE TITLE
[OTHER] App Customization

### ISSUE THREAD

**Issue by hiddener** [HemmeligOrg/Hemmelig.app#255]
### What would you like to share?

Hi, definitely not a bug. I've been playing with docker and this app for a day, still learning it. Now I have it up with docker compose:

```
services:
    hemmelig:
        image: hemmelig:latest-1 # Check the tags for what version to use
        container_name: customname
        hostname: hemmelig
        init: true
        volumes:
            - ./src/:/home/node/hemmelig/src/
            - ./public/:/home/node/hemmelig/public/
            - ./database/:/home/node/hemmelig/database/
        environment:
            - SECRET_LOCAL_HOSTNAME=localipv4 # The local hostname for the fastify instance
            - SECRET_PORT=3000 # The port number for the fastify instance
            - SECRET_HOST=custom.org # Used for i.e. set cors/cookies to your domain name
            - SECRET_ROOT_USER=customuser # User as the root admin user
            - SECRET_ROOT_PASSWORD=iamroot # The admin user password (change this after signed in)
            - SECRET_ROOT_EMAIL=admin@custom.org # The email for the admin user
            - SECRET_FILE_SIZE=4 # Set the total allowed upload file size in mb
            - SECRET_FORCED_LANGUAGE=en # Set the default language for the application
#            - SECRET_JWT_SECRET=!changeme! # Override this for the secret signin JWT tokens for log in
            - SECRET_MAX_TEXT_SIZE=256 # The max text size for the secret. Is set in kb. i.e. 256 for 256kb
        ports:
            - '3000:3000'
        networks:
            - public
        restart: always
#        stop_grace_period: 1m
        stop_grace_period: 10s
        healthcheck:
            test: 'wget -O /dev/null localhost:3000 || exit 1'
            timeout: 5s
            retries: 1

    caddy:
      image: caddy:latest
      container_name: caddy-customname
      restart: unless-stopped
      volumes:
        - ./Caddyfile:/etc/caddy/Caddyfile
        - ./caddy_data:/data
        -  - ./caddy_config:/config
      ports:
        - "80:80"
        - "443:443"
        - "443:443/udp"
      networks:
        - public

networks:
  public:
    external: true
```

First, I've tried to edit strings in `public/locales/en/translation.json` and `docker-compose down` + `docker-compose up -d --build`. I still see the original text.

Please, what I'm doing wrong? How to customize it?
