### ISSUE TITLE
Restricting to specific IP Adress not working in behind Traefik proxy

### ISSUE THREAD

**Issue by SajidK25** [HemmeligOrg/Hemmelig.app#267]
### Description

Hi, @bjarneo
Greeting! I have deployed Hemmelig.app  to my VPS behind a Traefik proxy. Everything is working well so far but Restricting  IP feature. When I generated a secret using that feature the secret could not be opened even there was no error message showed. Browser console showed a error
`Uncaught (in promise) SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON`

### Screenshots

![001  Secret not showing](https://github.com/HemmeligOrg/Hemmelig.app/assets/5094391/7fe177de-5f08-47bc-998a-07a60c0a8877)

![001  browser console error](https://github.com/HemmeligOrg/Hemmelig.app/assets/5094391/afeed383-f436-4d26-82f2-3fea97fc4559)

### Additional information

I have hemmelig with docker compose behind Traefik.

```
services:
    hemmelig:
        image: hemmeligapp/hemmelig:v5.19.4 # https://github.com/HemmeligOrg/Hemmelig.app/tags
        container_name: hemmeligapp
        hostname: hemmelig
        init: true
        volumes:
            - ./data/hemmelig/:/var/tmp/hemmelig/upload/files
            - ./database/:/home/node/hemmelig/database/
        environment:
            - SECRET_LOCAL_HOSTNAME=0.0.0.0 # The local hostname for the fastify instance
            - SECRET_PORT=3000 # The port number for the fastify instance
            - SECRET_HOST=!changeme! # Used for i.e. set cors/cookies to your domain name
            - SECRET_ROOT_USER=groot # User as the root admin user
            - SECRET_ROOT_PASSWORD=iamroot # The admin user password (change this after signed in)
            - SECRET_ROOT_EMAIL=groot@hemmelig.app # The email for the admin user
            - SECRET_FILE_SIZE=4 # Set the total allowed upload file size in mb
            - SECRET_FORCED_LANGUAGE=en # Set the default language for the application
            - SECRET_JWT_SECRET=!changeme! # Override this for the secret signin JWT tokens for log in
            - SECRET_MAX_TEXT_SIZE=256 # The max text size for the secret. Is set in kb. i.e. 256 for 256kb
        labels:
            traefik.docker.network: "traefik-net"
            traefik.enable: "true"
            traefik.http.routers.hm.entrypoints: "https"
            traefik.http.routers.hm.middlewares: "default@file"
            traefik.http.routers.hm.rule: "Host(`${PROJECT_DOMAIN}`)"
            traefik.http.routers.hm.tls.certresolver: "letsEncrypt"
            traefik.http.routers.hm.tls.options: "modern@file"
            traefik.http.routers.hm.tls: "true"
            traefik.http.services.hm.loadbalancer.server.port: 3000
            traefik.http.services.hm.loadbalancer.sticky.cookie.httpOnly: "true"
            traefik.http.services.hm.loadbalancer.sticky.cookie.secure: "true"
        networks:
            - traefik-net
        ports:
            - '3002:3000'
        restart: always
        stop_grace_period: 1m
        healthcheck:
            test: 'wget -O /dev/null localhost:3000 || exit 1'
            timeout: 5s
            retries: 1
networks:
  traefik-net:
    external: true 
```
My Traefik header configuration:-
```
 default:
      chain:
        middlewares:
          - default-security-headers
          - hemmelig
          - error-pages
          - gzip
   
    default-security-headers:
      headers:
        browserXssFilter: true                           
        contentTypeNosniff: true                    
        forceSTSHeader: true                              
        frameDeny: true                                   
        referrerPolicy: "strict-origin-when-cross-origin"
        sslRedirect: true                                
        stsIncludeSubdomains: true                      
        stsPreload: true                                  
        stsSeconds: 63072000                              
      
    hemmelig:
      headers:
        referrerPolicy: "no-referrer"
        browserXSSFilter: true
        contentTypeNosniff: true
        customFrameOptionsValue: "SAMEORIGIN"
        customRequestHeaders: 
          X-Forwarded-Proto: https
          forwardedHeaders:
            insecure: true
          proxyProtocol:
            insecure: true
```
