### ISSUE TITLE
Minified React error #301

### ISSUE THREAD

**Issue by trulow** [HemmeligOrg/Hemmelig.app#292]
### Description

When logging into the admin account and trying to access the Users tab, the following error appears instead of loading the page.

**`Unexpected Application Error!`**

**`Minified React error #301; visit https://reactjs.org/docs/error-decoder.html?invariant=301 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.`**

```
sd@https://<domain>.com/assets/index-06c76a10.js:37:52913
zc@https://<domain>.com/assets/index-06c76a10.js:37:62346
Hy@https://<domain>.com/assets/index-06c76a10.js:41:9293
Fy@https://<domain>.com/assets/index-06c76a10.js:41:949
kb@https://<domain>.com/assets/index-06c76a10.js:41:877
ci@https://<domain>.com/assets/index-06c76a10.js:41:729
qc@https://<domain>.com/assets/index-06c76a10.js:39:10813
py/<@https://<domain>.com/assets/index-06c76a10.js:37:38697
e.unstable_runWithPriority@https://<domain>.com/assets/index-06c76a10.js:26:3860
En@https://<domain>.com/assets/index-06c76a10.js:37:38475
py@https://<domain>.com/assets/index-06c76a10.js:37:38645
mr@https://<domain>.com/assets/index-06c76a10.js:37:38578
Gr@https://<domain>.com/assets/index-06c76a10.js:39:8417
fd@https://<domain>.com/assets/index-06c76a10.js:37:58185
nN/O</<@https://<domain>.com/assets/index-06c76a10.js:121:2496
nN/y<@https://<domain>.com/assets/index-06c76a10.js:121:2166
nN/O<@https://<domain>.com/assets/index-06c76a10.js:121:2489
pj/Me/<@https://<domain>.com/assets/index-06c76a10.js:102:13361
Me@https://<domain>.com/assets/index-06c76a10.js:102:13349
Rt@https://<domain>.com/assets/index-06c76a10.js:102:14641
_r@https://<domain>.com/assets/index-06c76a10.js:102:17375
```

### Additional information

This is deployed using docker-compose
```

services:
    hemmelig:
        container_name: hemmelig-app
        image: hemmeligapp/hemmelig:latest # https://github.com/HemmeligOrg/Hemmelig.app/tags
        hostname: hemmelig
        init: true
        volumes:
            - ./data/hemmelig/:/var/tmp/hemmelig/upload/files
            - ./database/:/home/node/hemmelig/database/
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/CITY
            - SECRET_LOCAL_HOSTNAME=0.0.0.0 # The local hostname for the fastify instance
            - SECRET_PORT=3000 # The port number for the fastify instance
            - SECRET_HOST=domain.com # Used for i.e. set cors/cookies to your domain name
            - SECRET_ROOT_USER=ADMIN # User as the root admin user
            - SECRET_ROOT_PASSWORD=PASSWD # The admin user password (change this after signed in)
            - SECRET_ROOT_EMAIL=test@gmail.com # The email for the admin user
            - SECRET_FILE_SIZE=4 # Set the total allowed upload file size in mb
            - SECRET_FORCED_LANGUAGE=en # Set the default language for the application
            - SECRET_JWT_SECRET=RANDOM_KEY # Override this for the secret signin JWT tokens for log in
            - SECRET_MAX_TEXT_SIZE=256 # The max text size for the secret. Is set in kb. i.e. 256 for 256kb
        ports:
            - '3000:3000'
        restart: always
        stop_grace_period: 1m
        healthcheck:
            test: 'wget -O /dev/null localhost:3000/api/healthz || exit 1'
            timeout: 5s
```
