### ISSUE TITLE
[FEATURE] Make the the app accessible on a subfolder ? 

### ISSUE THREAD

**Issue by tholeb** [HemmeligOrg/Hemmelig.app#338]
### What would you like to share?

Hello, I would like to make hemmelig accessible on a subfolder : host.name/hemmelig/ 

I tried to set `SECRET_HOST: host.name/hemmelig/` but I when I access the endpoint, all the files point to `/`, resulting in `404` : 
- /static/manifest.json
- /static/index-XXXYYY.css
- /static/index-XXXYYY.js

How can I make hemmelig accessible on a subfolder ? 

### Additional information

My container env : 

```yaml
hemmelig_app_env:
  SECRET_LOCAL_HOSTNAME: 0.0.0.0
  SECRET_PORT: "3000"
  SECRET_HOST: "host.name/hemmelig/"
  SECRET_ROOT_USER: bla
  SECRET_ROOT_PASSWORD: password
  SECRET_FILE_SIZE: "4"
  SECRET_JWT_SECRET: "random"
  SECRET_MAX_TEXT_SIZE: "256"

```
